travis:
  secure:
    BINSTAR_TOKEN: equ+IsSf11bPKKo0qSnr7qrqBO8YpV8JLI/zRL2NC9h7ufQZecvEcjwBl457tqXDSIELFWJWV7Ne7+INf9ZhYexTSD6IwXWNWh+hETno5JsS5izhc5Ei9sNDMDb2wwgumIQM5AnyFKFcEyORZ15qju6NQjLUtTYtm63UA/I2zsp5qnQhfkuS6q2bSy+MKzbCJgLK0GSMgiOovahxC0ehhMhucgccmuTvBZHzFRHFuu3niCmrkyAbX5zNJzQTOTn3HHmduQk6DJJWqRwIpBlaqZocT5usPHe7dSeMoFmomSXNBAQPVVOLd2wjtNoHIyjoPzUBs/gXqhO1v6HgU+RgEtCJDMzcsocRFqp/IAM/7jE2tijvZqf3zks5h5khh9rSKpABMg6oCrqaffI19YEiN/j8+lgMD0bB9wwrBFMYEJ8D54nLd7MuI+0XoW8OD2e7rBsmJSBHmMfX48OFxxoE3D/Dx+C8oEltKyjfZNlWytaH+hIod1JnXooudmhOG6Qlw5Hm1nWysznSB9bgasNMW6ar9SjVrXRnCi9Nv/Oa+pmGHtJO3fy2ycyZKpQp/W8cJtr1d0f0XMKgfdBA8FNXX9wCPWwIoEaAIv8KrRMaq5Y0btVF180u/488vax+A//AdpL2Qx6YpSbKNDEFtzTPdwjGmuH42pK52aD9UomdWYU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
